### ISSUE TITLE
Additional features - E-mail on expired/invalid token

### ISSUE THREAD

**Issue by VolkJ-VJ** [joaopsys/AutoChronoGG#13]
Hey. Please explain how to use this feature?

Optional: Additional features - E-mail on expired/invalid token

- Copy .config.example to .config
- Enable by setting email.enabled to true in .config.

**Comment by joaopsys** [comment]
Hi, I'm sorry I took so long to reply.

It's exactly how it's documented, but I can try to be more clear. 

In the same folder as your .py, you just need to create a .config folder with something like this inside:

```
{
  "email": {
    "enabled": true,
    "server": "gmail-smtp-in.l.google.com",
    "from": {
      "name": "AutoChronoGG",
      "address": "autochronogg@yourdomain.com"
    },
    "to": [
      {
        "name": "Your Name",
        "address": "yourname@yourdomain.com"
      }
    ]
  }
}
```

That Gmail SMTP server should work without authentication, however you will most likely need to add whatever 'from address' you choose to your contacts in the 'to address', or it will end up in the spam folder.

Since this is not really an issue, I will close it.
